project:
  debug: true

# Server configuration
rest:
  host: "localhost"
  port: 8080

# Database configuration and credentials
database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "password"
  name: "db_Astral"

admin:
  token: "T8UrXXFxHTxkW?x2PP-0fyfsYzDsxo7RwH6FNcZK=tX759FG!QxBQMGGkpVEBdVb"

# Logger configuration
logger:
  level: "INFO"
  rate: 1.0 # How many msgs to log

